version: '3'
services:
    #PHP Service
    app:
        build:
            context: .
            dockerfile: php/Dockerfile
        image: maintenance/php
        container_name: maintenance-php
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    #Nginx Service
    webserver:
        image: nginx:alpine
        container_name: maintenance-webserver
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html
            - ./nginx/conf.d/:/etc/nginx/conf.d/
    db:
        image: postgres:14.6
        container_name: maintenance-db
        restart: always
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - 5433:5433
        volumes:
            - ./postgres/:/docker-entrypoint-initdb.d/
